<script>
    require([
        'jquery',
        'Magento_Customer/js/customer-data'
    ], function ($, customerData) {

        /*  Reload cart when landed to the homepage 
            so the cart items added via productquiz will reflect
            on minicart
        */
        if ($(".cms-index-index").length) {
            var sections = ['cart'];
            customerData.reload(sections, true);	
        }
    });
</script>